networks:
  bank-api-network:
    driver: bridge

services:
  db:
    image: postgres
    networks:
      - bank-api-network
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis
    networks:
      - bank-api-network
    ports:
      - '6379:6379'

  api:
    build:
      context: "."
      dockerfile: ".docker/Dockerfile"
    networks:
      - bank-api-network
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./.gocache/pkg:/go/pkg
      - ./.ssh:/root/.ssh
      - ./:/opt/app/api
    ports:
      - '8080:8080'